INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");
INSERT INTO users (name) VALUES ("user 1");

INSERT INTO projects (title) VALUES ("title");
INSERT INTO projects (title) VALUES ("title");
INSERT INTO projects (title) VALUES ("title");
INSERT INTO projects (title) VALUES ("title");
INSERT INTO projects (title) VALUES ("title");
INSERT INTO projects (title) VALUES ("title");
INSERT INTO projects (title) VALUES ("title");
INSERT INTO projects (title) VALUES ("title");
INSERT INTO projects (title) VALUES ("title");
INSERT INTO projects (title) VALUES ("title");

INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
INSERT INTO pledges (amount) VALUES (5);
